### ISSUE TITLE
add documentation about the document types & format in Mongodb

### ISSUE THREAD

**Issue by monperrus** [Spirals-Team/repairnator#572]

**Comment by fermadeiral** [comment]
@surli, I saw you put this issue as minor priority, but I plan to check the types of info (e.g. runId) in each file we generate, to see if something important is missing, etc. In the middle of this task, it would be nice that I already document it, otherwise a duplicate effort will be put on it in the future. So I would like to ask you if you already have something in mind for this issue, so that way I could start by what you already think. If you don't have anything in mind, I will just start by myself, and then we can polish it in a PR.

**Comment by surli** [comment]
> if you already have something in mind for this issue

For me this documentation should be on the form of JSON schema for each collection we have in the database. And to add a README to document the purpose of each collection and how they can be related to each other. 

I put a minor priority but I'll certainly do it before the end of my contract to complete our documentation.

**Comment by fermadeiral** [comment]
Ok, I remember now the thing I wanted to talk to you: it's about this issue.

> For me this documentation should be on the form of JSON schema for each collection we have in the database. And to add a README to document the purpose of each collection and how they can be related to each other.

WDYT if I take just one collection, build the JSON schema for it, write a README to document the purpose of it, and then you review it for me in the next two days? Because then, you validating one, I do the other ones in the same style, and when you come back, it will be ready for all collections, only missing the part of the relation of them, which we can discuss later.

**Comment by surli** [comment]
> if I take just one collection, build the JSON schema for it, write a README to document the purpose of it, and then you review it for me in the next two days?

I'll only be able to validate it tomorrow, and you know that's my job to do that: I'm sure you have plenty of other things to do. Here I'm afraid you loose time for nothing.
