### ISSUE TITLE
question: how to contribute to the Repairnator project?

### ISSUE THREAD

**Issue by monperrus** [Spirals-Team/repairnator#579]
Hi all,

Are you excited by Repairnator? Do you want to contribute? We do welcome new contributors.

We have identified getting started issues, don't hesitate to ask questions on them, we will answer as fast as possible:

* https://github.com/Spirals-Team/repairnator/labels/good-first-issue
* https://github.com/Spirals-Team/npefix/labels/good-first-issue
* https://github.com/SpoonLabs/nopol/labels/good-first-issue

**Comment by surli** [comment]
We should put that in the readme

**Comment by fermadeiral** [comment]
Hi boys,

I propose we write some specific instructions for new contributors. For instance, I have played the role of contributor through a fork, and there is an issue by proposing PRs through a fork on repairnator: the build always break in Spirals-Team/repairnator because environment variables are not set when the build comes from a fork. Moreover, it's not possible to build in a different branch in repairnator's forks (due the config in .travis.yml). To overcome this issue and to propose PRs that produce passing builds, in my case, I open a PR in my own fork, thus the build is triggered in Travis. To show in my PR on Spirals-Team/repairnator that my changes don't break the build, I put a link to the PR on my fork (e.g. https://github.com/Spirals-Team/repairnator/pull/617), so Simon (mainly) can know that the master won't be break if he merges my PR.
Maybe there is some other way easier than the one I adopted. In any case, IMHO, it would be nice if we build instructions for things like that, to make everybody lifes easier (on the side of Spirals-Team/repairnator and also on the side of the contributors).

@btellstrom, please, consider reading this before proposing your first PR.

**Comment by surli** [comment]
In fact when discussing with @monperrus @btellstrom we propose that all of us (me, you @fermadeiral and @btellstrom) now directly use the repo repairnator and not a fork.

The process is then the following: 
 - we all work in our own branches, created on the repo Spirals-Team/repairnator
 - we create PR from those branches

Then TravisCI will be able to work properly without much work to do.

On the long term view, what we should really do is what I did on jTravis: we create proper real unit test that don't need to access to Github or Travis API, and we keep our current tests only as integration tests: then we only launch the unit tests on the PR, and the integration tests on master.

So I'll try to do #470 in that way.

**Comment by fermadeiral** [comment]
This simplifies a lot for me. Great, thanks for telling me.
