### ISSUE TITLE
high availability: deploy Repairnator in Kubernetes

### ISSUE THREAD

**Issue by gluckzhang** [Spirals-Team/repairnator#813]
Core design:

- A queue system like ActiveMQ to save build ids
- A K8s cron job running repairnator scaner to get latest build ids and add them into the queue
- A set of pods running repairnator pipeline which fetches build id from the queue and does the analysis

Such an architecture could decrease coupling and take advantages of Kubernetes features. Since Repairnator has already implemented different Docker images, it is not very difficult to push forward.

Tasks (one per pull requests):

* [x] Rename `BuildRunner` into `DockerPipelineRunner`
* [x] Create empty `ActiveMQPipelineRunner extends AbstractPoolManager` (branch by abstraction strategy)
* [x] Change field name of `DockerPipelineRunner` to  `pipelineRunner`
* [x] Add interface PipelineRunner for ActiveMQPipelineRunner to implements
* [x] Implement `ActiveMQPipelineRunner`
* [x] Add `NopeRunner` which does nothing. It would allow to run the scanner only, even without docker installed.
* [x] `NopeRunner` should be the default
* [x] Add support for configuring the runner to use (ie either `DockerPipelineRunner` or `ActiveMQPipelineRunner`)
* [x] Change Travis CI config to deploy an ActiveMQ there and test the core functionality

**Comment by btellstrom** [comment]
>* A queue system like ActiveMQ to save build ids
>* A K8s cron job running repairnator scaner to get latest build ids and add them into the queue

I believe these two things are already accomplished by the rt_scanner, which may be run indefinitely if one does not specify a duration.

Instead, I think that what needs to be done is to create a dockerimage with the rt-scanner. If I'm not completely wrong, we have the ability to run docker-containers remotely from rt-scanner? Which should allows us to create a set of pods to listen to the scanner. If I'm wrong about this, I know for a fact that we currently have an option to specify how many threads we wish to have running docker-containers, which we should be able to translate into instead communicating with Kubernetes.

**Comment by gluckzhang** [comment]
Yes, we need to create a dockerimage for the rt-scanner :)
I think that would be good if we could decouple these components a bit more. Currently the rt-scanner is responsible for everything, like fetching buildids from Travis, add them into the queue and create several pipeline containers to evaluate each build. If the rt-scanner is down, everything stops. If we move parts of orchestration work to Kubernetes, Repairnator has higher avaliablity. If there's is a new release for rt-scanner, it doesn't influence the queue system and pipelines which are running separately. We will be able to smoothly upgrade it, similarly to the pipeline dockerimage.

Back to @btellstrom 's questions, yes, I think we could run pipelines pods from rt-scanner pods. We could also create a set of pipeline pods to communicate with rt-scanner. But it sounds a bit weird that a rt-scanner is running two different services: scanner itself and a queue.

**Comment by gluckzhang** [comment]
Oh right, one more comment: when I mentioned "A K8s cron job running repairnator scaner", I mean rt-scanner. So a dockerimage for rt-scanner is definitely on the todo list :)

**Comment by gluckzhang** [comment]
Thanks for referring the file!  
It's not necessary to rely on K8s, because we could provide a DockerCompose file to run these components together. We could also modify the bash scripts a bit to run all the stuff. My suggestion is only to decouple rt-scanner. But the current setup is also nice and clear actually. Maybe we need more discussions here.

**Comment by btellstrom** [comment]
>  But the current setup is also nice and clear actually. Maybe we need more discussions here.

Just a name that seems slightly odd. 

We currently do have the dockerpool component, which we could perhaps alter to make sure that the rt-scanner instead communicates with K8S? Currently the queue-class is inheriting from that component .
```Java
public class BuildRunner extends AbstractPoolManager 
```
Perhaps we could extend this component to communicate with K8S and perhaps only need to add a new `BuildRunner` class in the actual rt-scanner? Alternatively create a `repairnator-K8S` component? Not sure exactly how K8S handle such things and how much would need to be added.

**Comment by gluckzhang** [comment]
I think that's a good idea. We could make rt-scanner configurable for BuildRunners. For K8s, the build runner only needs to push buildids to the queue, like a ActiveMq server whose host and username&password info are provided.
I'm not an expert in this field, but I think K8s only acts as a orchestrator, i.e. monitoring all kinds of pods and make sure they are self-healed to some extent. A good way is that only pods need to communicate with each other (rt-scanner, queue, pipeline). Applications should not care about where they are going to be deployed (Kubernetes, AWS etc). So when we implement this, we don't need to consider K8s, we only need to give address and username&password configuration to corresponding dockerimages.

**Comment by btellstrom** [comment]
> We could make rt-scanner configurable for BuildRunners.

I belive that we currently only use `initRunner()` and `submitBuild()` in `RTScanner` So that seems quite easy to achieve. Just let `initRunner()` handle the login details and put them in the configuration file of Repairnator? Or do you think it is possible to put them somewhere else, so that we do not add application specific options?

**Comment by gluckzhang** [comment]
> I belive that we currently only use `initRunner()` and `submitBuild()` in `RTScanner` So that seems quite easy to achieve. Just let `initRunner()` handle the login details and put them in the configuration file of Repairnator?

This sounds nice. I remember that somewhere we also allow users to specify MONGO_DB configurations, I think it's fine to add optional ActiveMq configuration. Or maybe another option, like `only_forwarding_buildid`, when it's true the `submitBuild()` method does need to create pipeline containers.

> Or do you think it is possible to put them somewhere else, so that we do not add application specific options?

I am not familar with this part, not sure about it yet :)

**Comment by btellstrom** [comment]
> This sounds nice. I remember that somewhere we also allow users to specify MONGO_DB configurations, I think it's fine to add optional ActiveMq configuration.

Very true.

> Or maybe another option, like only_`forwarding_buildid`, when it's true the `submitBuild()` method doesn't need to create pipeline containers.

Yeah, that would probably be a good idea.

**Comment by Tailp** [comment]
Added the documentation for how to deploy repairnator on K8s :) . 

Current objective: feature recommended by @gluckzhang to add some kind of monitor to periodically scan a repo like per commit by using webhook. 

Problems faced during the task: 
* RT scanner use docker containers during run. This creates problem to deploy it as a container deployed to K8s. It would mean that we run containers inside a container , which can result to some complex behaviors. - For some more details [link](https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/)

* RT scanner use an in-build queue which results to higher complexity. Instead of a global queue in ActiveMQ every one can listen to now we have tons of local queues and also each scanner need to look for the free pipeline to assign too which is unneccessaily tedious. 

Current solution:
* Deploy the repo scanner instead and scale it indivually in reference to a scenario where someone want to have their repo scanned then they will submit it on a webpage which direct this information to the queue of the repo scanner to check for builds. These builds will be submitted to the pipeline scanner for generating patches. Also the whitelisted builds scanned by the RTscanner can directly submit to the queue of the pipelines instead of the scanner for generating patches.

**Comment by monperrus** [comment]
Very good. Instead of adding things here, what about breaking this PR in smaller ones, to be merged one after the other? This is the "[branch by abstraction](https://martinfowler.com/bliki/BranchByAbstraction.html)" practice.

**Comment by gluckzhang** [comment]
> Very good. Instead of adding things here, what about breaking this PR in smaller ones, to be merged one after the other? This is the "[branch by abstraction](https://martinfowler.com/bliki/BranchByAbstraction.html)" practice.

Hi @monperrus , good idea. I also find that the PR is growing too fat now. We will break it into small ones :)

**Comment by Tailp** [comment]
@monperrus Yes sir, I'll do that with Long :) .

**Comment by Tailp** [comment]
Documentation and repo scanner added in this [fork](https://github.com/gluckzhang/repairnator/tree/kubernetes) :). Awaiting for verification and feedbacks. Next is to break down PR to smaller ones for merging as refering to [branch by abstraction](https://martinfowler.com/bliki/BranchByAbstraction.html).

**Comment by monperrus** [comment]
Modifying the top comment to identify subtasks that can be addressed in small pull requests.

**Comment by Tailp** [comment]
>     * Add `NopeRunner` which does nothing. It would allow to run the scanner only, even without docker installed.

Hi :),  currently I am able to implement ActiveMQPipelineRunner class without inheriting from dockerpool and it's still working properly. DockerPipelineRunner is still initialized but it's just a dummy since if kubernetesmode = true then it won't be using any feature . So I am pretty sure that in kubernetes mode no docker is required for ActiveMQPipelineRunner. Maybe this is the feature you want with the quoted task ? :) .

**Comment by monperrus** [comment]
good point, I agree with you. Maybe we can improve the hierarchy:

```
interface PipelineRunner
AbstractPoolManager implements PipelineRunner
DockerBuildRunner extends AbstractPoolManager 
NopeRunner implements PipelineRunner
ActiveMQPipelineRunner implements PipelineRunner
```

**Comment by Tailp** [comment]
Hi @monperrus , it is a bit troublesome due to AbstractPoolManager use different return object and input object types than ActiveMQPipelineRunner and NopeRunner. For instance: in AbstractPoolManager.java
```
public RunnablePipelineContainer submitBuild(String imageId, InputBuildId inputBuildId)
```
and in ActiveMQPipelineRunner.java
```
public void submitBuild(Build build)
```

So best choice is only do 
```
NopeRunner implements PipelineRunner
ActiveMQPipelineRunner implements PipelineRunner
```

**Comment by Tailp** [comment]
Hi @monperrus :), it is a bit troublesome due to AbstractPoolManager use different return object and input object types than ActiveMQPipelineRunner and NopeRunner. For instance: in AbstractPoolManager.java
```
public RunnablePipelineContainer submitBuild(String imageId, InputBuildId inputBuildId)
```
and in ActiveMQPipelineRunner.java
```
public void submitBuild(Build build)
```
So best choice is probably only to do

NopeRunner implements PipelineRunner
ActiveMQPipelineRunner implements PipelineRunner

I will proceed doing this. If you think it's not good then I can exclude it later in the main PR :) . It just take some minutes to make.

**Comment by monperrus** [comment]
Closing this one, thanks to the awesome #879
