### ISSUE TITLE
Faling test RTScanner requires new repo

### ISSUE THREAD

**Issue by btellstrom** [Spirals-Team/repairnator#860]
The test `testRepositoryWithoutCheckstyleIsInteresting` is currently failing since the (repo)[https://github.com/nosan/embedded-cassandra] has recently added checkstyle. We should find a new repo which fulfills the same criteria as this one used to do. More specifically it should:

* Be on travis
* Be written in Java
* Not have checkstyle enabled

(The list above might not be absolute and I might have missed some details).

**Comment by fermadeiral** [comment]
Hi, @btellstrom.

Repairnator will be always prone to have this type of failing test because the repo being used in the test can change. Finding another repo will only fix the test temporarily.

A suggestion that I have to give you is to checkout a commit from the repo, just after cloning it, where the checkstyle still didn't exist, so everything should be ok in the test.

Best,
Fernanda

**Comment by monperrus** [comment]
One way is to fork https://github.com/nosan/embedded-cassandra under the organization repairnator and force master to be at the right commit. The fork won't evolve anymore.

**Comment by btellstrom** [comment]
Hi @fermadeiral.

That is a very good point that I had not considered. However, I do think that Martins solution may be the easier here since the test is reliant on the slug to get the latest travis-build (might also be me not familiar with how to do it).

@monperrus I do not believe I am part of the repairnator organization, want to add me or should I just fork it myself?

**Comment by monperrus** [comment]
you're now a member!

**Comment by fermadeiral** [comment]
+1 to Martin's solution
